services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    image: llm-asg-gateway:step2.5
    ports:
      - "8000:8000"
    depends_on:
      - mock-llm
    environment:
      - POLICY_PATH=/app/configs/policy.yaml
      - LLM_ENDPOINT=http://mock-llm:8001/echo
      - LOG_DIR=/app/logs
      - STATIC_DIR=/app/static
      - ADMIN_TOKEN=changeme123
      # - MONITOR_ONLY=true
    volumes:
      - ./configs:/app/configs:ro
      - ./static:/app/static:ro
      - ./logs:/app/logs

  mock-llm:
    build:
      context: .
      dockerfile: Dockerfile.mockllm
    image: llm-asg-mock:step2.5
    ports:
      - "8001:8001"

